const trip={days:[
{d:1,date:'10 月 1 日',city:'伊斯坦布尔',route:'北京 → 伊斯坦布尔',core:'初见伊斯坦布尔 + 蓝色清真寺',must:['蓝色清真寺'],high:['圣索菲亚','地下水宫（可后移）'],optional:[],stay:'伊斯坦布尔（苏丹艾哈迈德 / 锡尔凯吉优先，酒店 TBD）',note:'07:20 北京首都 T3 起飞；约 12:50 当地落地。落地后轻松活动，适应时差。'},
{d:2,date:'10 月 2 日',city:'伊斯坦布尔',route:'伊斯坦布尔老城',core:'托普卡帕宫',must:['托普卡帕宫'],high:[],optional:['居尔哈内公园','大巴扎','香料市场','苏莱曼尼耶清真寺日落'],stay:'伊斯坦布尔（酒店 TBD）',note:'不叠加伊斯坦布尔考古博物馆，避免连续逛馆疲劳。'},
{d:3,date:'10 月 3 日',city:'厄吕代尼兹',route:'伊斯坦布尔 → 达拉曼 → 费特希耶 → 厄吕代尼兹',core:'进入地中海模式 + 开始自驾',must:['厄吕代尼兹'],high:['滑翔伞（天气、时间、体力合适再参加）'],optional:[],stay:'厄吕代尼兹（酒店 TBD）',note:'国内航班 TBD；上午抵达达拉曼优先。Cizgi 达拉曼机场取自动挡车。'},
{d:4,date:'10 月 4 日',city:'D400 → 卡什',route:'厄吕代尼兹 → 蝴蝶谷悬崖 → D400 → 卡尔坎 → 卡普塔什海滩 → 卡什',core:'整趟旅行最重要的自驾日',must:['D400 山海公路','卡普塔什海滩','卡什'],high:['蝴蝶谷悬崖'],optional:['卡尔坎','帕塔拉古城'],stay:'卡什（酒店 TBD）',note:'唯一硬指标：晚上住进卡什。沿途可随时停车、喝咖啡、看风景，不设小时表。'},
{d:5,date:'10 月 5 日',city:'安塔利亚 → 格雷梅',route:'卡什 → D400 → 安塔利亚机场 → 开塞利 → 格雷梅',core:'继续 D400 + 还车和转场',must:[],high:[],optional:['米拉古城（时间不足直接取消）'],stay:'格雷梅洞穴酒店 · 第 1/3 晚（酒店 TBD）',note:'Cizgi 安塔利亚机场异地还车；安塔利亚→开塞利航班 TBD；落地后预约接送。'},
{d:6,date:'10 月 6 日',city:'卡帕多奇亚',route:'格雷梅及周边',core:'热气球第一次机会',must:['热气球（超级必打卡）','格雷梅露天博物馆','格雷梅日落观景台 / 恋人山'],high:[],optional:['爱情谷或玫瑰谷，只选一个'],stay:'格雷梅洞穴酒店 · 第 2/3 晚（酒店 TBD）',note:'若热气球取消，保留 10/7 第二次机会；若成功，早餐后可补觉，不从凌晨暴走到晚上。'},
{d:7,date:'10 月 7 日',city:'卡帕多奇亚',route:'格雷梅及周边',core:'热气球备用 / 老爷车 + 地下城',must:['代林库尤或凯马克勒地下城二选一'],high:['老爷车追热气球（仅 10/6 热气球已成功）'],optional:['乌奇希萨尔','鸽子谷','阿瓦诺斯','回酒店休息'],stay:'格雷梅洞穴酒店 · 第 3/3 晚（酒店 TBD）',note:'固定优先级：热气球 > 老爷车追气球。老爷车不能抢占第二次热气球机会。'},
{d:8,date:'10 月 8 日',city:'伊斯坦布尔',route:'卡帕多奇亚 → 内夫谢希尔机场 → 伊斯坦布尔',core:'慢慢告别卡帕多奇亚',must:[],high:[],optional:['补前两天喜欢但没去的地方'],stay:'伊斯坦布尔（酒店 TBD）',note:'内夫谢希尔→伊斯坦布尔航班 TBD；下午 / 傍晚航班优先。'},
{d:9,date:'10 月 9 日',city:'伊斯坦布尔',route:'考古博物馆 → 卡拉柯伊 / 加拉塔 → 博斯普鲁斯',core:'考古博物馆 + 博斯普鲁斯日落游船',must:['伊斯坦布尔考古博物馆','博斯普鲁斯海峡日落游船（超级必打卡）'],high:[],optional:['卡拉柯伊','加拉塔街区','加拉塔塔（排队不长再登）'],stay:'伊斯坦布尔（酒店 TBD）',note:'游船目标覆盖白天、日落、蓝调和两岸亮灯；晚上安排稍好的最后晚餐。'},
{d:10,date:'10 月 10 日',city:'伊斯坦布尔',route:'酒店 → 伊斯坦布尔机场 → 成都 → 北京',core:'离境',must:[],high:[],optional:[],stay:'返程途中',note:'15:40 当地起飞；不安排正式景点；建议 10:00—10:30 离开酒店。'}],
tips:[
{cat:'钱与支付',title:'机场取土耳其里拉',status:'已确认',text:'落地伊斯坦布尔机场后优先找 VakıfBank（瓦克夫银行）ATM；首次取 5,000—6,000 TRY。不够后续再取。遇到 Currency Conversion 时选择 TRY、Without Conversion / Decline Conversion，拒绝 DCC 人民币动态换汇。'},
{cat:'钱与支付',title:'准备 500 欧元现金',status:'当前计划',text:'国内提前准备 500 EUR 备用，主要用于热气球等欧元报价项目；现金价可能更优，但不代表一定全部花掉，最终以供应商规则为准。'},
{cat:'手机网络',title:'A2644 不支持 eSIM',status:'已确认',text:'iPhone 13 Pro Max 国行 A2644 使用实体旅游 Nano SIM；优先能接入 Turkcell 的产品，10 天建议至少 20GB 且支持热点。国内号保留收短信，关闭数据漫游，可开最低限度国际漫游备用。'},
{cat:'租车',title:'Cizgi 自动挡自驾',status:'部分待确认',text:'10/3 达拉曼机场取车、10/5 安塔利亚机场异地还车；主驾驶为中国 C2，只租自动挡。下单前需 Cizgi 书面确认中国驾照原件 + 英文翻译件及招行 Amex 是否可用。'},
{cat:'预订',title:'Klook 只作为比价渠道',status:'已确认',text:'可用于热气球、老爷车、滑翔伞、接送和门票；方便但不默认最便宜。高价项目同时比较 Klook、官网、酒店 / 当地代理。'},
{cat:'天气',title:'10 月初穿衣重点',status:'行李参考',text:'伊斯坦布尔白天约 18—23℃、早晚 12—16℃且可能秋雨；D400 白天约 24—28℃；格雷梅白天约 18—22℃，热气球凌晨约 5—9℃，重点防风、分层穿衣。'},
{cat:'天气',title:'热气球重点看风',status:'出发前核验',text:'真正需要重点关注的是 10/6—10/7 清晨风况。实时天气不得提前写死，临近出发再核验。'},
{cat:'体验规则',title:'热气球优先于老爷车',status:'固定规则',text:'10/6 若热气球取消，10/7 继续坐热气球；只有 10/6 已成功，10/7 清晨才安排老爷车追气球。'},
{cat:'保险',title:'项目保险不能替代旅行险',status:'高风险',text:'需购买完整境外旅行保险，覆盖医疗、紧急救援等；如果参加滑翔伞，应明确覆盖滑翔伞 / 高风险运动。'}],
tbd:['10/3 伊斯坦布尔 → 达拉曼国内航班','10/5 安塔利亚 → 开塞利国内航班','10/8 内夫谢希尔 → 伊斯坦布尔国内航班','所有酒店','Cizgi 具体车型 / 价格 / 保险','Cizgi 对中国驾照翻译件的书面确认','Cizgi 是否接受招行 Amex','热气球公司和价格','老爷车供应商','是否最终参加滑翔伞','实体 SIM 具体商品','旅行保险产品','博斯普鲁斯日落游船具体班次','景点最终开放时间与票价','临近出发的实际天气']};

const groups=[
['护照与入境',[['护照有效期检查（两本均至 2045 年）',1],['出发前检查护照无严重破损'],['检查空白页'],['护照资料页手机备份'],['护照资料页云端备份'],['打印护照复印件'],['打印 / 离线保存往返机票'],['打印 / 离线保存酒店订单'],['打印 / 离线保存简版行程'],['出发前再次核验中国普通护照赴土耳其最新入境政策',0,1]]],
['信用卡与现金',[['主驾驶本人名下实体信用卡',1],['向 Cizgi 书面确认是否接受招行 Amex',0,1],['准备本人名下 Visa / Mastercard 实体卡备用'],['确认境外交易已开启'],['确认额度充足与 PIN'],['两人银行卡分开放'],['现金与卡分开放'],['机场取 5,000—6,000 TRY'],['国内准备 500 EUR 现金']]],
['驾照与租车',[['中国 C2 驾照原件'],['驾照正反面复印件'],['英文驾照翻译件'],['Cizgi 租车订单'],['书面确认中国驾照 + 英文翻译件是否认可',0,1],['确认异地还车费、保险和免赔额'],['确认玻璃 / 轮胎 / 底盘是否覆盖'],['确认 HGS、油量政策与门店位置'],['确认营业时间及延误等候规则'],['订单填写实际航班号'],['取车时拍全车视频'],['记录车身、轮毂、轮胎、玻璃和保险杠'],['记录车顶、内饰、油量、里程和既有损伤']]],
['电话卡与离线',[['已确认 A2644 不支持 eSIM',1],['购买土耳其实体验游 Nano SIM'],['确认实际接入网络，优先 Turkcell'],['确认 ≥20GB 且支持热点'],['国内手机号保留收验证码'],['关闭国内号数据漫游'],['开通最低限度国际漫游备用'],['下载 Google Maps 离线地图'],['下载 Google Translate 土耳其语离线包']]],
['旅行保险',[['两人购买境外旅行保险',0,1],['覆盖境外医疗与紧急救援',0,1],['覆盖航班 / 行李延误与旅行中断'],['核对热气球是否承保',0,1],['核对滑翔伞 / 高风险运动是否承保',0,1],['保单手机保存并云端备份']]],
['体验预订',[['选择正规热气球公司',0,1],['比较 Klook / 官网 / 酒店代理'],['确认热气球价格、支付与保险'],['优先预订 10/6，10/7 保留备用',0,1],['仅 10/6 热气球成功后安排 10/7 老爷车',0,1],['确认老爷车是否含摄影师'],['滑翔伞按 10/3 天气和时间决定'],['确认滑翔伞运营商基础保险']]],
['电子设备与用品',[['欧标转换插头（Type C/F）'],['充电宝'],['车载充电线'],['备用手机线'],['泳衣'],['防风外套'],['薄羽绒 / 抓绒'],['长裤'],['舒服步行鞋'],['折叠伞 / 轻便雨衣'],['常用药'],['晕车 / 晕船药备用']]],
['出发前 72 小时',[['国际航班值机'],['复核三段土耳其国内航班',0,1],['复核酒店与 Cizgi 订单'],['复核驾照翻译材料'],['复核信用卡额度'],['复核热气球订单',0,1],['复核开塞利 → 格雷梅接送'],['复核手机网络和离线地图'],['复核旅行保险生效日期',0,1],['复核伊斯坦布尔与 D400 天气'],['重点关注格雷梅 10/6—10/7 风况',0,1]]]];

const key='turkiye-2026-checks-v1',favKey='turkiye-2026-favs-v1';let saved={},favs=[];try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){}try{favs=JSON.parse(localStorage.getItem(favKey)||'[]')}catch(e){}
const idFor=(g,i)=>'g'+g+'i'+i;const isDone=(g,i,initial)=>Object.prototype.hasOwnProperty.call(saved,idFor(g,i))?saved[idFor(g,i)]:!!initial;
const allChecks=()=>groups.flatMap((g,gi)=>g[1].map((item,i)=>({gi,i,item,done:isDone(gi,i,item[1])})));
function progress(){const all=allChecks(),done=all.filter(x=>x.done).length,p=Math.round(done/all.length*100);['home','check'].forEach(n=>{const r=document.getElementById(n+'-ring');r.style.setProperty('--p',p);r.dataset.label=p+'%';document.getElementById(n+'-bar').style.width=p+'%'});homeCount.textContent=done+' / '+all.length;homeProgressText.textContent='已完成 '+done+' 项';checkProgressText.textContent=p+'% 已完成';checkSummary.textContent=done+' 项完成 · '+(all.length-done)+' 项待办';const next=all.find(x=>!x.done);nextTask.textContent=next?next.item[0]:'全部完成，准备出发！'}
function renderDays(){routeMap.innerHTML=['伊斯坦布尔','达拉曼','D400','安塔利亚','卡帕多奇亚','伊斯坦布尔'].map((x,i,a)=>`<span class="route-stop">${x}</span>${i<a.length-1?'<span class="route-arrow">›</span>':''}`).join('');dayList.innerHTML=trip.days.map(d=>`<article class="day-card"><button class="day-summary" aria-expanded="false"><span class="day-no">D${d.d}</span><span class="day-title"><b>${d.date} · ${d.city}</b><small>${d.core}</small></span><span class="chev">⌄</span></button><div class="day-detail"><div class="mini-core"><small>今日唯一核心</small><b>${d.core}</b></div><div class="chips">${d.must.map(x=>`<span class="tag must">必打卡 · ${x}</span>`).join('')}${d.high.map(x=>`<span class="tag high">高优先级 · ${x}</span>`).join('')}${d.optional.map(x=>`<span class="tag optional">随缘 · ${x}</span>`).join('')}</div><p class="stay">🚗 ${d.route}<br>🏨 ${d.stay}</p><div class="alert"><b>提醒</b><span>${d.note}</span></div></div></article>`).join('');document.querySelectorAll('.day-summary').forEach(b=>b.onclick=()=>{const c=b.parentElement;c.classList.toggle('open');b.setAttribute('aria-expanded',c.classList.contains('open'))})}
let pendingOnly=false,allOpen=true;function renderChecks(){checkGroups.innerHTML=groups.map((g,gi)=>{const done=g[1].filter((x,i)=>isDone(gi,i,x[1])).length;return `<section class="check-group"><button class="group-head"><b>${g[0]}</b><span>${done} / ${g[1].length}　⌄</span></button><div class="group-items">${g[1].map((x,i)=>{const done=isDone(gi,i,x[1]);return `<label class="check-item ${pendingOnly&&done?'hidden':''}"><input data-g="${gi}" data-i="${i}" type="checkbox" ${done?'checked':''}><span class="checkbox">✓</span><span class="check-text">${x[0]}${x[2]?'<em class="risk">重点</em>':''}</span></label>`}).join('')}</div></section>`}).join('');checkGroups.querySelectorAll('.group-head').forEach(b=>b.onclick=()=>{b.nextElementSibling.hidden=!b.nextElementSibling.hidden});checkGroups.querySelectorAll('input').forEach(input=>input.onchange=()=>{saved[idFor(input.dataset.g,input.dataset.i)]=input.checked;localStorage.setItem(key,JSON.stringify(saved));renderChecks();progress()});progress()}
let tipCat='全部';function renderTips(){const cats=['全部',...new Set(trip.tips.map(x=>x.cat))];tipFilters.innerHTML=cats.map(x=>`<button class="filter ${x===tipCat?'active':''}" data-cat="${x}">${x}</button>`).join('');tipFilters.querySelectorAll('button').forEach(b=>b.onclick=()=>{tipCat=b.dataset.cat;renderTips()});const tips=trip.tips.map((x,i)=>({...x,i})).filter(x=>tipCat==='全部'||x.cat===tipCat);tipsList.innerHTML=tips.map(x=>`<article class="tip"><div class="tip-top"><span class="tag">${x.cat} · ${x.status}</span><div class="tip-actions"><button class="icon-btn ${favs.includes(x.i)?'saved':''}" data-fav="${x.i}" aria-label="收藏">☆</button><button class="icon-btn" data-copy="${x.i}" aria-label="复制">⧉</button></div></div><h3>${x.title}</h3><p>${x.text}</p></article>`).join('');document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const i=+b.dataset.fav;favs=favs.includes(i)?favs.filter(x=>x!==i):[...favs,i];localStorage.setItem(favKey,JSON.stringify(favs));renderTips()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const x=trip.tips[+b.dataset.copy];try{await navigator.clipboard.writeText(x.title+'\n'+x.text);toast('已复制到剪贴板')}catch(e){toast('长按文字即可复制')}})}
function focusToday(){const now=new Date(),start=new Date('2026-10-01T00:00:00+08:00'),end=new Date('2026-10-11T00:00:00+03:00');let idx=0;if(now>=start&&now<end)idx=Math.min(9,Math.floor((now-start)/86400000));else if(now>=end)idx=9;const d=trip.days[idx],days=Math.ceil((start-now)/86400000);daysLeft.textContent=days>0?days:(now<end?'旅中':'✓');countdownLabel.textContent=days>0?'距出发':(now<end?'旅行进行中':'旅程完成');focusKicker.textContent=(days>0?'出发前预览':'今日行程')+' · D'+d.d;focusCity.textContent=d.city;focusCore.textContent=d.core;focusRoute.textContent=d.route;focusStay.textContent=d.stay;focusNote.textContent=d.note}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id==='screen-'+name));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));scrollTo({top:0,behavior:'smooth'})}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
const ids=['home-count','home-progress-text','check-progress-text','check-summary','next-task','route-map','day-list','check-groups','tip-filters','tips-list','days-left','countdown-label','focus-kicker','focus-city','focus-core','focus-route','focus-stay','focus-note'];ids.forEach(id=>window[id.replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=document.getElementById(id));
const expandAll=document.getElementById('expand-all'),tbdList=document.getElementById('tbd-list');
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>show(b.dataset.screen));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{pendingOnly=b.dataset.filter==='pending';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderChecks()});expandAll.onclick=()=>{allOpen=!allOpen;document.querySelectorAll('.group-items').forEach(x=>x.hidden=!allOpen);expandAll.textContent=allOpen?'全部收起':'全部展开'};
tbdList.innerHTML=trip.tbd.map(x=>`<div class="tbd-row"><b>TBD</b><span>${x}</span></div>`).join('');focusToday();renderDays();renderChecks();renderTips();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');

