const trip={days:[
{d:1,date:'10 月 1 日',city:'伊斯坦布尔',route:'北京 → 伊斯坦布尔',core:'初见伊斯坦布尔 + 蓝色清真寺',must:['蓝色清真寺'],high:['圣索菲亚','地下水宫（可后移）'],optional:[],stay:'伊斯坦布尔（苏丹艾哈迈德 / 锡尔凯吉优先，酒店 TBD）',note:'07:20 北京首都 T3 起飞；约 12:50 当地落地。落地后轻松活动，适应时差。'},
{d:2,date:'10 月 2 日',city:'伊斯坦布尔',route:'伊斯坦布尔老城',core:'托普卡帕宫',must:['托普卡帕宫'],high:[],optional:['居尔哈内公园','大巴扎','香料市场','苏莱曼尼耶清真寺日落'],stay:'伊斯坦布尔（酒店 TBD）',note:'不叠加伊斯坦布尔考古博物馆，避免连续逛馆疲劳。'},
{d:3,date:'10 月 3 日',city:'厄吕代尼兹',route:'伊斯坦布尔 → 达拉曼 → 费特希耶 → 厄吕代尼兹',core:'进入地中海模式 + 开始自驾',must:['厄吕代尼兹'],high:['滑翔伞（天气、时间、体力合适再参加）'],optional:[],stay:'厄吕代尼兹（酒店 TBD）',note:'国内航班 TBD；上午抵达达拉曼优先。Cizgi 达拉曼机场取自动挡车。'},
{d:4,date:'10 月 4 日',city:'D400 → 卡什',route:'厄吕代尼兹 → 蝴蝶谷悬崖 → D400 → 卡尔坎 → 卡普塔什海滩 → 卡什',core:'整趟旅行最重要的自驾日',must:['D400 山海公路','卡普塔什海滩','卡什'],high:['蝴蝶谷悬崖'],optional:['卡尔坎','帕塔拉古城'],stay:'卡什（酒店 TBD）',note:'唯一硬指标：晚上住进卡什。沿途可随时停车、喝咖啡、看风景，不设小时表。'},
{d:5,date:'10 月 5 日',city:'安塔利亚 → 格雷梅',route:'卡什 → D400 → 安塔利亚机场 → 开塞利 → 格雷梅',core:'继续 D400 + 还车和转场',must:[],high:[],optional:['米拉古城（时间不足直接取消）'],stay:'格雷梅洞穴酒店 · 第 1/3 晚（酒店 TBD）',note:'Cizgi 安塔利亚机场异地还车；安塔利亚→开塞利航班 TBD；落地后预约接送。'},
{d:6,date:'10 月 6 日',city:'卡帕多奇亚',route:'格雷梅及周边',core:'热气球第一次机会',must:['热气球（超级必打卡）','格雷梅露天博物馆','格雷梅日落观景台 / 恋人山'],high:[],optional:['爱情谷或玫瑰谷，只选一个'],stay:'格雷梅洞穴酒店 · 第 2/3 晚（酒店 TBD）',note:'若热气球取消，保留 10/7 第二次机会；若成功，早餐后可补觉，不从凌晨暴走到晚上。'},
{d:7,date:'10 月 7 日',city:'卡帕多奇亚',route:'格雷梅及周边',core:'热气球备用 / 老爷车 + 地下城',must:['代林库尤或凯马克勒地下城二选一'],high:['老爷车追热气球（仅 10/6 热气球已成功）'],optional:['乌奇希萨尔','鸽子谷','阿瓦诺斯','回酒店休息'],stay:'格雷梅洞穴酒店 · 第 3/3 晚（酒店 TBD）',note:'固定优先级：热气球 > 老爷车追气球。老爷车不能抢占第二次热气球机会。'},
{d:8,date:'10 月 8 日',city:'伊斯坦布尔',route:'卡帕多奇亚 → 内夫谢希尔机场 → 伊斯坦布尔',core:'慢慢告别卡帕多奇亚',must:[],high:[],optional:['补前两天喜欢但没去的地方'],stay:'伊斯坦布尔（酒店 TBD）',note:'内夫谢希尔→伊斯坦布尔航班 TBD；下午 / 傍晚航班优先。'},
{d:9,date:'10 月 9 日',city:'伊斯坦布尔',route:'考古博物馆 → 卡拉柯伊 / 加拉塔 → 博斯普鲁斯',core:'考古博物馆 + 博斯普鲁斯日落游船',must:['伊斯坦布尔考古博物馆','博斯普鲁斯海峡日落游船（超级必打卡）'],high:[],optional:['卡拉柯伊','加拉塔街区','加拉塔塔（排队不长再登）'],stay:'伊斯坦布尔（酒店 TBD）',note:'游船目标覆盖白天、日落、蓝调和两岸亮灯；晚上安排稍好的最后晚餐。'},
{d:10,date:'10 月 10 日',city:'伊斯坦布尔',route:'酒店 → 伊斯坦布尔机场 → 成都 → 北京',core:'离境',must:[],high:[],optional:[],stay:'返程途中',note:'15:40 当地起飞；不安排正式景点；建议 10:00—10:30 离开酒店。'}],
tips:[
{cat:'钱与支付',title:'机场取土耳其里拉',status:'已确认',text:'落地伊斯坦布尔机场后优先找 VakıfBank（瓦克夫银行）ATM；首次取 5,000—6,000 TRY。不够后续再取。遇到 Currency Conversion 时选择 TRY、Without Conversion / Decline Conversion，拒绝 DCC 人民币动态换汇。'},
{cat:'钱与支付',title:'准备 500 欧元现金',status:'当前计划',text:'国内提前准备 500 EUR 备用，主要用于热气球等欧元报价项目；现金价可能更优，但不代表一定全部花掉，最终以供应商规则为准。'},
{cat:'手机网络',title:'A2644 不支持 eSIM',status:'已确认',text:'iPhone 13 Pro Max 国行 A2644 使用实体旅游 Nano SIM；优先能接入 Turkcell 的产品，10 天建议至少 20GB 且支持热点。国内号保留收短信，关闭数据漫游，可开最低限度国际漫游备用。'},
{cat:'租车',title:'Cizgi 自动挡自驾',status:'部分待确认',text:'10/3 达拉曼机场取车、10/5 安塔利亚机场异地还车；主驾驶为中国 C2，只租自动挡。下单前需 Cizgi 书面确认中国驾照原件 + 英文翻译件及招行 Amex 是否可用。'},
{cat:'预订',title:'Klook 只作为比价渠道',status:'已确认',text:'可用于热气球、老爷车、滑翔伞、接送和门票；方便但不默认最便宜。高价项目同时比较 Klook、官网、酒店 / 当地代理。'},
{cat:'天气',title:'10 月初穿衣重点',status:'行李参考',text:'伊斯坦布尔白天约 18—23℃、早晚 12—16℃且可能秋雨；D400 白天约 24—28℃；格雷梅白天约 18—22℃，热气球凌晨约 5—9℃，重点防风、分层穿衣。'},
{cat:'天气',title:'热气球重点看风',status:'出发前核验',text:'真正需要重点关注的是 10/6—10/7 清晨风况。实时天气不得提前写死，临近出发再核验。'},
{cat:'体验规则',title:'热气球优先于老爷车',status:'固定规则',text:'10/6 若热气球取消，10/7 继续坐热气球；只有 10/6 已成功，10/7 清晨才安排老爷车追气球。'},
{cat:'保险',title:'项目保险不能替代旅行险',status:'高风险',text:'需购买完整境外旅行保险，覆盖医疗、紧急救援等；如果参加滑翔伞，应明确覆盖滑翔伞 / 高风险运动。'}],
tbd:['10/3 伊斯坦布尔 → 达拉曼国内航班','10/5 安塔利亚 → 开塞利国内航班','10/8 内夫谢希尔 → 伊斯坦布尔国内航班','所有酒店','Cizgi 具体车型 / 价格 / 保险','Cizgi 对中国驾照翻译件的书面确认','Cizgi 是否接受招行 Amex','热气球公司和价格','老爷车供应商','是否最终参加滑翔伞','实体 SIM 具体商品','旅行保险产品','博斯普鲁斯日落游船具体班次','景点最终开放时间与票价','临近出发的实际天气']};

const dayGuides=[
{images:['assets/itinerary/istanbul-blue-mosque.jpg','assets/itinerary/istanbul-water.jpg'],captions:['蓝色清真寺 · 初见伊斯坦布尔','博斯普鲁斯与老城天际线'],play:['落地后的第一天只安排老城轻松散步，先把时差和旅途疲惫放下。','蓝色清真寺注意礼拜时段与着装，现场开放情况临近出发再确认。','如果精神状态好再去地下水宫，不把“抵达日”排成赶场日。']},
{images:['assets/itinerary/istanbul-water.jpg','assets/itinerary/istanbul-blue-mosque.jpg'],captions:['从水边看伊斯坦布尔','苏丹艾哈迈德的城市轮廓'],play:['托普卡帕宫预留半天，重点看宫廷空间、珍宝与博斯普鲁斯视野。','下午把时间留给居尔哈内公园、香料市场或一杯土耳其咖啡。','这一天不叠加考古博物馆，让人文体验有呼吸感。']},
{images:['assets/itinerary/oludeniz-aerial.jpg','assets/itinerary/oludeniz-coast.jpg'],captions:['厄吕代尼兹 · 地中海蓝','海边与山谷之间'],play:['优先选上午抵达达拉曼的航班，取车后不再安排复杂景点。','滑翔伞只在天气、时间和体力都合适时参加；不合适就留在海边。','取车时拍摄全车视频，重点记录轮胎、玻璃、轮毂和已有划痕。']},
{images:['assets/itinerary/oludeniz-coast.jpg','assets/itinerary/oludeniz-aerial.jpg'],captions:['D400 · 山海公路的蓝','沿着海岸慢慢开'],play:['这天不做小时级时间表，漂亮海湾、咖啡馆和观景点都可以临时停。','卡普塔什停车困难时不要为机位冒险，安全和体验比照片更重要。','唯一硬指标是天黑前住进卡什，晚上只逛港口和老城小巷。']},
{images:['assets/itinerary/oludeniz-coast.jpg','assets/itinerary/cappadocia-valley.jpg'],captions:['D400 的最后一段海岸','从地中海转场到格雷梅'],play:['沿途停留服从航班和还车时间，米拉古城时间不够就直接取消。','安塔利亚机场还车前补足油量，并预留检查车辆与办理手续的时间。','开塞利落地后直接接送前往格雷梅，洞穴酒店连续住三晚。']},
{images:['assets/cappadocia-hero.jpg','assets/itinerary/cappadocia-museum.jpg'],captions:['卡帕多奇亚 · 热气球清晨','格雷梅岩窟与大地色'],play:['热气球是全程最高优先级，前一晚尽早休息并等待运营方确认。','若顺利飞行，早餐后可以补觉，不需要从凌晨一直逛到晚上。','下午看格雷梅露天博物馆，爱情谷和玫瑰谷只选一个。']},
{images:['assets/itinerary/underground-city.jpg','assets/itinerary/cappadocia-valley.jpg'],captions:['地下城 · 岩层下的世界','卡帕多奇亚的山谷与光'],play:['如果前一天热气球取消，今天继续等第二次机会，老爷车自动让位。','地下城只选代林库尤或凯马克勒其中一个，避免重复和体力消耗。','下午可以去乌奇希萨尔、鸽子谷，也可以回酒店喝咖啡。']},
{images:['assets/itinerary/cappadocia-valley.jpg','assets/itinerary/bosphorus-ferry.jpg'],captions:['慢慢告别卡帕多奇亚','飞回伊斯坦布尔'],play:['上午睡醒再出门，补一个真正喜欢却没来得及去的地方。','优先选择内夫谢希尔机场的下午或傍晚航班，减少无效等待。','回到伊斯坦布尔后只安排晚餐和附近散步。']},
{images:['assets/itinerary/bosphorus-sunset.jpg','assets/itinerary/bosphorus-ferry.jpg'],captions:['博斯普鲁斯 · 日落收尾','渡轮穿过伊斯坦布尔'],play:['上午把两到三小时完整留给伊斯坦布尔考古博物馆。','下午在卡拉柯伊与加拉塔慢慢走，排队太长就不登塔。','日落游船最好覆盖白天、落日、蓝调与两岸亮灯四个时段。']},
{images:['assets/itinerary/bosphorus-ferry.jpg','assets/itinerary/istanbul-water.jpg'],captions:['最后一次看博斯普鲁斯','把旅程带回家'],play:['上午不安排正式景点，只吃早餐、附近散步和整理行李。','建议 10:00—10:30 离开酒店，为国际航班留足余量。','把票据、照片和重要文件分别备份，再慢慢和城市告别。']}
];
let selectedItineraryDay=0,galleryIndex=0;

const groups=[
['护照与入境',[['护照有效且有空白页（两本均至 2045 年）',1],['护照无严重破损，原件随身携带'],['护照、机票、酒店与简版行程完成手机及云端离线备份'],['出发前复核中国普通护照赴土耳其最新入境政策',0,1]]],
['信用卡与现金',[['主驾驶本人名下实体信用卡',1],['向 Cizgi 书面确认招行 Amex，并另备 Visa / Mastercard',0,1],['开启境外交易，确认额度与 PIN'],['准备 500 EUR；落地取 5,000—6,000 TRY，并拒绝 DCC']]],
['驾照与租车',[['中国 C2 驾照原件、英文翻译件与复印件',0,1],['向 Cizgi 书面确认驾照材料及自动挡车型',0,1],['确认车型、异地还车费、保险免赔、HGS 与油量政策'],['订单填写实际航班号，并确认延误等候与门店时间'],['取车拍全车视频，记录油量、里程与既有损伤']]],
['电话卡与离线',[['已确认 A2644 不支持 eSIM',1],['购买 ≥20GB、支持热点、优先 Turkcell 的实体 Nano SIM'],['国内号保留收验证码，并关闭数据漫游'],['下载 Google Maps 离线地图与 Translate 土耳其语包']]],
['旅行保险',[['两人购买境外旅行保险',0,1],['确认境外医疗与紧急救援额度',0,1],['确认航班 / 行李延误与旅行中断保障'],['确认热气球及滑翔伞等高风险运动承保',0,1]]],
['核心体验',[['选择正规热气球公司，优先预订 10/6、10/7 备用',0,1],['确认热气球价格、取消规则、支付方式与保险'],['仅在 10/6 热气球成功后安排 10/7 老爷车'],['滑翔伞按天气和体力决定，并确认基础保险']]],
['关键装备',[['欧标 Type C/F 转换插头、充电宝与车载充电'],['防风分层衣物、舒适步行鞋与轻便雨具'],['常用药与晕车 / 晕船药']]],
['出发前 72 小时',[['完成国际值机，并复核三段土耳其国内航班',0,1],['复核全部酒店、Cizgi 与接送订单'],['复核热气球订单及集合通知',0,1],['确认保险生效、电话卡、离线地图与重要凭证'],['复核伊斯坦布尔、D400 天气及 10/6—10/7 格雷梅风况',0,1]]]];

const key='turkiye-2026-checks-v2',favKey='turkiye-2026-favs-v1',tbdKey='turkiye-2026-tbd-v1';let saved={},favs=[],tbdSaved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){}try{favs=JSON.parse(localStorage.getItem(favKey)||'[]')}catch(e){}try{tbdSaved=JSON.parse(localStorage.getItem(tbdKey)||'{}')}catch(e){}
const idFor=(g,i)=>'g'+g+'i'+i;const isDone=(g,i,initial)=>Object.prototype.hasOwnProperty.call(saved,idFor(g,i))?saved[idFor(g,i)]:!!initial;
const allChecks=()=>groups.flatMap((g,gi)=>g[1].map((item,i)=>({gi,i,item,done:isDone(gi,i,item[1])})));
function progress(){const all=allChecks(),done=all.filter(x=>x.done).length,p=Math.round(done/all.length*100);['home','check'].forEach(n=>{const r=document.getElementById(n+'-ring');r.style.setProperty('--p',p);r.dataset.label=p+'%';document.getElementById(n+'-bar').style.width=p+'%'});homeCount.textContent=done+' / '+all.length;homeProgressText.textContent='已完成 '+done+' 项';checkProgressText.textContent=p+'% 已完成';checkSummary.textContent=done+' 项完成 · '+(all.length-done)+' 项待办';const next=all.find(x=>!x.done);nextTask.textContent=next?next.item[0]:'全部完成，准备出发！'}
function renderDays(){const tabs=document.getElementById('day-tabs'),stage=document.getElementById('itinerary-stage'),d=trip.days[selectedItineraryDay],guide=dayGuides[selectedItineraryDay];tabs.innerHTML=trip.days.map((item,i)=>`<button class="date-tab ${i===selectedItineraryDay?'active':''}" data-day="${i}" aria-pressed="${i===selectedItineraryDay}"><small>D${item.d}</small><b>${item.date.replace(' 月 ','/').replace(' 日','')}</b><span>${item.city.replace(' → ','·')}</span></button>`).join('');stage.innerHTML=`<article class="day-feature"><div class="day-gallery"><img src="${guide.images[galleryIndex]}" alt="${guide.captions[galleryIndex]}"><div class="gallery-shade"></div><div class="gallery-caption"><small>D${d.d} · ${d.date}</small><strong>${guide.captions[galleryIndex]}</strong></div><button class="gallery-arrow prev" aria-label="上一张照片">‹</button><button class="gallery-arrow next" aria-label="下一张照片">›</button><div class="gallery-dots">${guide.images.map((_,i)=>`<button class="${i===galleryIndex?'active':''}" data-slide="${i}" aria-label="查看第 ${i+1} 张照片"></button>`).join('')}</div></div><div class="day-story"><p class="eyebrow">DAY ${String(d.d).padStart(2,'0')} · ${d.date}</p><h2>${d.city}</h2><div class="day-core"><small>今天唯一的核心</small><strong>${d.core}</strong></div><div class="priority-tags">${d.must.map(x=>`<span class="tag must">必打卡 · ${x}</span>`).join('')}${d.high.map(x=>`<span class="tag high">高优先级 · ${x}</span>`).join('')}${d.optional.map(x=>`<span class="tag optional">随缘 · ${x}</span>`).join('')}</div><section class="play-card"><small>怎么玩</small>${guide.play.map((x,i)=>`<p><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></p>`).join('')}</section><div class="journey-facts"><div><small>路线</small><b>${d.route}</b></div><div><small>今晚住</small><b>${d.stay}</b></div></div><div class="day-reminder"><b>出发前记得</b><span>${d.note}</span></div><div class="day-switch"><button ${selectedItineraryDay===0?'disabled':''} data-shift="-1">← 前一天</button><span>${d.d} / ${trip.days.length}</span><button ${selectedItineraryDay===trip.days.length-1?'disabled':''} data-shift="1">后一天 →</button></div></div></article>`;tabs.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selectedItineraryDay=+b.dataset.day;galleryIndex=0;renderDays();document.querySelector('.date-tab.active')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})});stage.querySelector('.gallery-arrow.prev').onclick=()=>{galleryIndex=(galleryIndex-1+guide.images.length)%guide.images.length;renderDays()};stage.querySelector('.gallery-arrow.next').onclick=()=>{galleryIndex=(galleryIndex+1)%guide.images.length;renderDays()};stage.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{galleryIndex=+b.dataset.slide;renderDays()});stage.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{selectedItineraryDay+=+b.dataset.shift;galleryIndex=0;renderDays();document.querySelector('.day-tabs-wrap')?.scrollIntoView({behavior:'smooth',block:'start'})})}
let pendingOnly=false,allOpen=true;function renderChecks(){checkGroups.innerHTML=groups.map((g,gi)=>{const done=g[1].filter((x,i)=>isDone(gi,i,x[1])).length;return `<section class="check-group"><button class="group-head"><b>${g[0]}</b><span>${done} / ${g[1].length}　⌄</span></button><div class="group-items">${g[1].map((x,i)=>{const done=isDone(gi,i,x[1]);return `<label class="check-item ${pendingOnly&&done?'hidden':''}"><input data-g="${gi}" data-i="${i}" type="checkbox" ${done?'checked':''}><span class="checkbox">✓</span><span class="check-text">${x[0]}${x[2]?'<em class="risk">重点</em>':''}</span></label>`}).join('')}</div></section>`}).join('');checkGroups.querySelectorAll('.group-head').forEach(b=>b.onclick=()=>{b.nextElementSibling.hidden=!b.nextElementSibling.hidden});checkGroups.querySelectorAll('input').forEach(input=>input.onchange=()=>{saved[idFor(input.dataset.g,input.dataset.i)]=input.checked;localStorage.setItem(key,JSON.stringify(saved));renderChecks();progress()});progress()}
let tipCat='全部';function renderTips(){const cats=['全部',...new Set(trip.tips.map(x=>x.cat))];tipFilters.innerHTML=cats.map(x=>`<button class="filter ${x===tipCat?'active':''}" data-cat="${x}">${x}</button>`).join('');tipFilters.querySelectorAll('button').forEach(b=>b.onclick=()=>{tipCat=b.dataset.cat;renderTips()});const tips=trip.tips.map((x,i)=>({...x,i})).filter(x=>tipCat==='全部'||x.cat===tipCat);tipsList.innerHTML=tips.map(x=>`<article class="tip"><div class="tip-top"><span class="tag">${x.cat} · ${x.status}</span><div class="tip-actions"><button class="icon-btn ${favs.includes(x.i)?'saved':''}" data-fav="${x.i}" aria-label="收藏">☆</button><button class="icon-btn" data-copy="${x.i}" aria-label="复制">⧉</button></div></div><h3>${x.title}</h3><p>${x.text}</p></article>`).join('');document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const i=+b.dataset.fav;favs=favs.includes(i)?favs.filter(x=>x!==i):[...favs,i];localStorage.setItem(favKey,JSON.stringify(favs));renderTips()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const x=trip.tips[+b.dataset.copy];try{await navigator.clipboard.writeText(x.title+'\n'+x.text);toast('已复制到剪贴板')}catch(e){toast('长按文字即可复制')}})}
function focusToday(){const now=new Date(),start=new Date('2026-10-01T00:00:00+08:00'),end=new Date('2026-10-11T00:00:00+03:00');let idx=0;if(now>=start&&now<end)idx=Math.min(9,Math.floor((now-start)/86400000));else if(now>=end)idx=9;const d=trip.days[idx],days=Math.ceil((start-now)/86400000);daysLeft.textContent=days>0?days:(now<end?'旅中':'✓');countdownLabel.textContent=days>0?'距出发':(now<end?'旅行进行中':'旅程完成');focusKicker.textContent=(days>0?'出发前预览':'今日行程')+' · D'+d.d;focusCity.textContent=d.city;focusCore.textContent=d.core;focusRoute.textContent=d.route;focusStay.textContent=d.stay;focusNote.textContent=d.note}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id==='screen-'+name));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));scrollTo({top:0,behavior:'smooth'})}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
function renderTbd(){const done=trip.tbd.filter((_,i)=>tbdSaved[i]).length;tbdStatus.textContent=done+' / '+trip.tbd.length;tbdList.innerHTML=trip.tbd.map((x,i)=>{const confirmed=!!tbdSaved[i];return `<label class="tbd-row ${confirmed?'confirmed':''}"><input type="checkbox" data-tbd="${i}" ${confirmed?'checked':''}><span class="tbd-check">✓</span><span class="tbd-copy">${x}</span>${confirmed?'<small>已确认</small>':''}</label>`}).join('');tbdList.querySelectorAll('[data-tbd]').forEach(input=>input.onchange=()=>{tbdSaved[input.dataset.tbd]=input.checked;localStorage.setItem(tbdKey,JSON.stringify(tbdSaved));renderTbd();toast(input.checked?'已标记为已确认':'已恢复为待确认')})}
const ids=['home-count','home-progress-text','check-progress-text','check-summary','next-task','check-groups','tip-filters','tips-list','days-left','countdown-label','focus-kicker','focus-city','focus-core','focus-route','focus-stay','focus-note'];ids.forEach(id=>window[id.replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=document.getElementById(id));
const expandAll=document.getElementById('expand-all'),tbdList=document.getElementById('tbd-list'),tbdStatus=document.getElementById('tbd-status');
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>show(b.dataset.screen));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{pendingOnly=b.dataset.filter==='pending';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderChecks()});expandAll.onclick=()=>{allOpen=!allOpen;document.querySelectorAll('.group-items').forEach(x=>x.hidden=!allOpen);expandAll.textContent=allOpen?'全部收起':'全部展开'};
renderTbd();focusToday();renderDays();renderChecks();renderTips();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');

